[project]
name = "i-unipile-sdk"
version = "0.1.0"
description = "Python SDK for interacting with Unipile API."
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "httpx>=0.28.1",
    "pydantic>=2.10.6",
]
